# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
        {id: 11, size: 0.15},
        {id: 5, size: 0.15},
        {id: 16, size: 0.15},
        {id: 25, size: 0.48},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
#tag_bundles:
#  [
#    {
#      name: 'charging_pad',
#      layout:
#        [
#          {id: 9,  size: 0.1},
#          {id: 2,  size: 0.1, x: -0.05625, y:  0.1125},
#          {id: 13, size: 0.1, x:  0.05625, y:  0.1125},
#          {id: 0,  size: 0.1, x: -0.05625, y: -0.1125},
#          {id: 4,  size: 0.1, x:  0.05625, y: -0.1125}
#        ]
#    }
#  ]
tag_bundles:
 [
#   {
#     name: 'charging_pad',
#     layout:
#       [
#         {id: 9, size: 0.15},
#         {id: 11, size: 0.15, x: 0.0047, y: 0.5709, z: -0.0009, qw: 0.9987, qx: 0.0506, qy: -0.0057, qz: -0.0005},
#         {id: 5, size: 0.15, x: -0.2904, y: 0.5747, z: 0.0030, qw: 0.9998, qx: 0.0061, qy: 0.0171, qz: -0.0054},
#         {id: 16, size: 0.15, x: 0.2830, y: 0.5703, z: -0.0179, qw: 1.0000, qx: -0.0031, qy: 0.0036, qz: -0.0052},
#         {id: 25, size: 0.48, x: -0.0007, y: 0.9912, z: -0.0122, qw: 0.7085, qx: 0.0093, qy: 0.0014, qz: 0.7056}
#       ]
#   }
]
