# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
       # {id: 10, size: 0.15},
       # {id: 5, size: 0.15},
       # {id: 11, size: 0.15},
       # {id: 16, size: 0.15},
       # {id: 25, size: 0.48}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
#tag_bundles:
#  [
#    {
#      name: 'charging_pad',
#      layout:
#        [
#          {id: 9,  size: 0.1},
#          {id: 2,  size: 0.1, x: -0.05625, y:  0.1125},
#          {id: 13, size: 0.1, x:  0.05625, y:  0.1125},
#          {id: 0,  size: 0.1, x: -0.05625, y: -0.1125},
#          {id: 4,  size: 0.1, x:  0.05625, y: -0.1125}
#        ]
#    }
#  ]
tag_bundles:
  [
    {
      name: 'charging_pad',
      layout:
        [
          {id: 5, size: 0.15, x: -0.2541, y: 0.4854, z: 0.0, qw: 1.0000, qx: -0.0030, qy: 0.0007, qz: -0.0004},
          {id: 11, size: 0.15, x: 0.0421, y: 0.4854, z: 0.0, qw: 1.0000, qx: -0.0044, qy: -0.0026, qz: 0.0033},
          {id: 16, size: 0.15, x: 0.3211, y: 0.4854, z: 0.0, qw: 1.0000, qx: -0.0011, qy: -0.0015, qz: -0.0004},
          {id: 25, size: 0.48, x: 0.0336, y: 0.9046, z: 0.0, qw: 0.7052, qx: -0.0083, qy: -0.0071, qz: 0.7089}
        ]
    }
  ]
