# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
#    {id: 9, size: 0.1},
#    {id: 2, size: 0.22},
#    {id: 13, size: 0.22},
#    {id: 0, size: 0.22},
#    {id: 4, size: 0.22}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'charging_pad',
      layout:
         [
          {id: 9,  size: 0.1},
          {id: 2,  size: 0.22, x: -0.3137, y: 0.3075, z: 0.0055},
          {id: 13, size: 0.22, x: 0.3132, y: 0.3183, z: -0.0071},
          {id: 0,  size: 0.22, x: -0.3086, y: -0.3185, z: 0.0002},
          {id: 4,  size: 0.22, x: 0.3191, y: -0.3109, z: -0.0099}
         ]
    }
  ]
#tag_bundles:
#  [
#    {
#      name: 'charging_pad',
#      layout:
#        [
#          {id: 9,  size: 0.1},
#          {id: 2,  size: 0.1, x: -0.05625, y:  0.1125},
#          {id: 13, size: 0.1, x:  0.05625, y:  0.1125},
#          {id: 0,  size: 0.1, x: -0.05625, y: -0.1125},
#          {id: 4,  size: 0.1, x:  0.05625, y: -0.1125}
#        ]
#    }
#  ]
